twig:
    file_name_pattern: '*.twig'
    form_themes: ['form_div_layout.html.twig','form_table_layout.html.twig','bootstrap_5_horizontal_layout.html.twig']

when@test:
    twig:
        strict_variables: true
